### ISSUE TITLE
Melhorias no código

### ISSUE THREAD

**Issue by hebertrfreitas** [victorvieiradev/jogo-da-adivinhacao-em-java#1]
@victorvieiradev  vou colocar aqui algumas sugestões de melhorias.

Neste trecho: https://github.com/victorvieiradev/jogo-da-adivinhacao-em-java/blob/fb9b16ff307222e239e812eb46ab4cfb464f90dc/src/Game.java#L16

O teste pode ser simplesmente assim:
```
if( ! startGame )
```
Assim o código se parece mais com uma expressão falada, algo como "se não iniciei o game".

Aqui neste outro trecho: https://github.com/victorvieiradev/jogo-da-adivinhacao-em-java/blob/fb9b16ff307222e239e812eb46ab4cfb464f90dc/src/Game.java#L30

É uma boa prática fazer a comparação com o lado que estático na esquerda, então ficaria assim:

```
if ("s".equalsIgnoreCase(op)){
```
porque se o valor de `op` for nulo (não seja este seja o caso aqui) você receberá um `NullPointerException`, já desta nova forma sua condição apenas será falsa.

**Comment by victorvieiradev** [comment]
Modificações realizadas, obrigado.
